"""empty message

Revision ID: 70a9124bdcd4
Revises: 2de6cb7e71c7
Create Date: 2023-04-15 14:40:25.325228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70a9124bdcd4'
down_revision = '2de6cb7e71c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), server_default='이 곳은 정말 좋습니다.', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
